version: '3'

services:
  reverse_proxy:
    image: nginx
    volumes:
     - ./nginx.template:/etc/nginx/conf.d/nginx.template:ro
     - ./index.html:/etc/nginx/html/index.html:ro
    env_file:
      - .env
    ports:
      - "${NGINX_ADDRESS}:${NGINX_PORT}:${NGINX_PORT}"
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$BACKEND_PORT' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  backend_service:
    image: python:2
    expose:
      - "${BACKEND_PORT}"
    volumes:
      - ./app:/app
    working_dir: /app
    command: "python -m SimpleHTTPServer ${BACKEND_PORT}"
