version: '3'

services:
  reverse_proxy:
    image: nginx
    userns_mode: host
    volumes:
     - ./nginx.template:/etc/nginx/conf.d/nginx.template:ro
    env_file:
      - .env
    ports:
      - "${NGINX_ADDRESS}:${NGINX_PORT}:${NGINX_PORT}"
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$BACKEND_PORT' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - frontend
      - backend

  backend_service:
    image: python
    userns_mode: host
    expose:
      - "${BACKEND_PORT}"
    volumes:
      - ./app:/app
    working_dir: /app
    command: "python -mhttp.server ${BACKEND_PORT}"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true
