version: '3'

services:
  reverse_proxy:
    image: reverse_proxy
    build:
      context: ./reverse_proxy
    read_only: true
    volumes:
      - /var/cache/nginx
      - /var/run
      - /etc/nginx/conf.d
    env_file:
      - .env
    ports:
      - "${NGINX_ADDRESS}:${NGINX_PORT}:${NGINX_PORT}"
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$BACKEND_PORT' < /etc/nginx/conf.d/reverse_proxy.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - frontend
      - backend

  backend_service:
    image: backend_service
    build:
      context: ./backend_service
    expose:
      - "${BACKEND_PORT}"
    working_dir: /app
    command: "python -mhttp.server ${BACKEND_PORT}"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true
